config/routes.rb
Rails.application.routes.draw do
  root 'dishes#index'
  get 'dishes/index' => 'dishes#index'
  resources :courses
  resources :dishes

end

app/models/course.rb
class Course < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  has_many :dishes
end

app/models/dish.rb
class Dish < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  belongs_to :course
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name)
    end
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :set_dish, only: [:show, :edit, :update, :destroy]

  # GET /dishes
  # GET /dishes.json
  def index
    @dishes = Dish.all
    @courses = Course.all
  end

  # GET /dishes/1
  # GET /dishes/1.json
  def show
    redirect_to edit_dish_path(@dish)
  end

  # GET /dishes/new
  def new
    @dish = Dish.new(:course_id=>params[:course_id])
  end

  # GET /dishes/1/edit
  def edit
  end

  # POST /dishes
  # POST /dishes.json
  def create
    @dish = Dish.new(dish_params)

    respond_to do |format|
      if @dish.save
        format.html { redirect_to root_path(@dish), notice: 'Dish was successfully created.' }
        format.json { render :show, status: :created, location: @dish }
      else
        format.html { render :new }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dishes/1
  # PATCH/PUT /dishes/1.json
  def update
    respond_to do |format|
      if @dish.update(dish_params)
        format.html { redirect_to @dish, notice: 'Dish was successfully updated.' }
        format.json { render :show, status: :ok, location: @dish }
      else
        format.html { render :edit }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dishes/1
  # DELETE /dishes/1.json
  def destroy
    @dish.destroy
    respond_to do |format|
      format.html { redirect_to dishes_url, notice: 'Dish was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dish
      @dish = Dish.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dish_params
      params.require(:dish).permit(:price, :name, :description, :course_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, {:style=>'color:#99AAEE'} %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Courses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.name %></td>
        <td><%= link_to 'Show', course %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @course.name %>
</p>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>

app/views/dishes/_form.html.erb
<%= form_for(@dish, url: dishes_path(@dish)) do |f| %>
  <% if @dish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dish.errors.count, "error") %> prohibited this dish from being saved:</h2>

      <ul>
      <% @dish.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= f.label :price, {:style=>'color:#99AAEE'} %><br>
      <%= f.text_field :price %>
    </div>

    <div class="field">
      <%= f.label :name, {:style=>'color:#99AAEE'} %><br>
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :description, {:style=>'color:#99AAEE'} %><br>
      <%= f.text_area :description %>
    </div>

    <div class="field">
      <%= f.label :course_id, {:style=>'color:#99AAEE'} %><br>
      <%= f.text_field :course_id, :readonly => true %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/dishes/edit.html.erb
<h1 id="form_label">Editing Dish</h1>

<%= render 'form' %>
<%= button_to "Delete", @dish, :method => :delete %>
<%= link_to 'Back', dishes_path %>

app/views/dishes/index.html.erb
<p id="notice"><%= notice %></p>

<div class="col-md-12">
  <h1 id="menu_main">Menu<i class="glyphicon glyphicon-cutlery"></i></h1>
</div>
<div class="col-md-2">
</div>
<div class="col-md-10" id="menu_whole">
  <%@courses.each_slice(2) do |courses|%>
    <div class="row">
      <%courses.each do |course|%>
        <div class="col-md-6" id="menu_section">
          <span id="food_label"><%=course.name%></br></span>
          <%= image_tag asset_url("image#{course.id}.jpg"), id: "food"%></br>
            <%course.dishes.each do |dish|%>
              <span id="dish"><%=link_to dish.name, edit_dish_path(dish), {:style=>'color:#99AAEE; font-family:fantasy'}%></span></br>
              <span id="price"><%p = dish.price%><%=number_to_currency(p)%></span></br>
              <span id="description"><%=dish.description%></span></br></br>
            <%end%>
            <span id="plus"><i class="glyphicon glyphicon-plus"></i></span>
            <span id="new_dish">
              <%= link_to 'New Dish', new_dish_path(course_id: course.id), {:style=>'color:#99AAEE;'} %>
            </span>
          </div>
      <%end%>
    </div>
  <%end%>
</div>

app/views/dishes/new.html.erb
<h1 id="form_label">New Dish</h1>

<%= render 'form' %>

<%= link_to 'Back', dishes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RestaurantMenu</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <%= yield %>
</div>

</body>
</html>